name: Posts

on:
  schedule:
    - cron: "0 0 * * *" # 00:00 UTC (07:00 Bangkok Time)
  workflow_dispatch:

jobs:
  fetch-posts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install gspread google-auth requests

      - name: Fetch recent posts
        env:
          SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
          X_BEARER: ${{ secrets.X_BEARER }}
          X_COOKIE_STRING: ${{ secrets.X_COOKIE_STRING }}
          X_AUTH_TOKEN: ${{ secrets.X_AUTH_TOKEN }}
          X_CT0: ${{ secrets.X_CT0 }}
        run: python post.py
